spring.application.name=pokebaralho-api
spring.datasource.url=jdbc:postgresql://<SEU_HOST_NEON>:5432/<NOME_DO_BANCO>?sslmode=require
spring.datasource.username=<SEU_USUARIO_NEON>
spring.datasource.password=<SUA_SENHA_NEON>
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true